### ISSUE TITLE
Snake Movement

### ISSUE THREAD

**Issue by iamRahulKumarr** [Gaurav18199/Snake-Game.github.io#1]
The movement of the snake has a bug.

 **Movements**:-
-top
-left
-right
-bottom

**Bug**:- The snake must not move directly towards Right if moving towards Left and Similarly for top and bottom.

**Comment by Gaurav18199** [comment]
fixed

**Comment by Gaurav18199** [comment]
bug fixed

**Comment by Gaurav18199** [comment]
bug fixed
